# Hetionet NQR test configuration

# Data and model paths
data_path: "data/hetionet"
kbc_path: "checkpoints/hetionet/hetionet_ComplEx_Rank1000_RegN3_Lmbda0.05_W0.1/model.pt"

# Model parameters
fraction: 10
thrshd: 0.001
neg_scale: 6

# Test settings
do_test: true
preference: "mixed"
reranker: "nqr"
checkpoint: "results/hetionet/nqr/valid/hetionet_10_0.001_nqr_0.001_0.1_mixed_1761052001_6u03z5mc/6u03z5mc-model.pt"
