# Hetionet Ranknet train configuration

# Data and model paths
data_path: "data/hetionet"
kbc_path: "checkpoints/hetionet/hetionet_ComplEx_Rank1000_RegN3_Lmbda0.05_W0.1/model.pt"

# Model parameters
fraction: 10
thrshd: 0.001
neg_scale: 6

# Training settings
do_train: true
tasks: "1p"
preference: "mixed"
reranker: "ranknet"
batch_size: 128
num_epochs: 10
wandb: true
